name: Build Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --target web
      working-directory: ./automata
    - name: Copy to web folder
      run: cp -R automata/pkg web/pkg
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4.0.0
      with:
        name: github-pages
        path: web
    - name: Deploy Github pages
      uses: actions/deploy-pages@v4
